### ISSUE TITLE
node LTS (v12.18.3 sep-2020) and node-sass  "4.7.2" don't compile.

### ISSUE THREAD

**Issue by juanmafont** [back4app/ionic-quickstart-example#2]
Hello, I try to install ionic-quickstart-example and always give me the same error when execute 'npm install'

I'm using actual LTS node (v.12.18.3 at sept-2020) and script always try to use node-sass 4.7.2. 

  See https://www.npmjs.com/package/node-sass

   The minimum node-sass version must be 4.12+

No matter I delete node_modules and I try to install node-sass 4.12 versions, always try to compile with node-sass 4.7.2  (maybe hard reference into source code)

The error is when try to compile (there are several errors, but always about 'nan' code):

Error->
/nan/nan.h:1044:37: error: cannot convert ‘char*’ to ‘v8::Isolate*’

Searching into internet, look like is incompatibilty between node  and node-sass versions.

**Comment by juanmafont** [comment]
From https://github.com/ionic-team/ionic-app-scripts#disclaimer-no-longer-maintained

> Oh, hello there! Ionic App Scripts is a tool tied specifically to version 3.x of Ionic Framework. Since the release of version 4.0 of Ionic Framework, we are no longer using Ionic App Scripts for building in Ionic Framework. Version 3 of Ionic Framework is no longer actively maintained by us. For more information on which versions are active, see our support policy. Due to this, we are no longer maintaining Ionic App Scripts and we recommend developers update their apps to the latest framework release. This provides several new features, bug fixes, performance improvements, as well as up to date tooling for Ionic apps. For more details on how to upgrade, check out our migration guide.

**Comment by juanmafont** [comment]
How fix this situation:

- curl -LOk https://github.com/back4app/ionic-quickstart-example/archive/master.zip && unzip master.zip
- cd ionic-quickstart-example-master
- edit package.json      Change line 36 "@ionic/app-scripts": "3.1.9",  to "@ionic/app-scripts": "3.2.4",
- run now "npm installl"
